addSbtPlugin("org.scala-native"          % "sbt-scala-native"              % "0.4.11")
addSbtPlugin("org.portable-scala"        % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"                    % "4.1.1")
addSbtPlugin("org.typelevel"             % "sbt-typelevel-github-actions"  % "0.4.19")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.5.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"                  % "0.10.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.4.1")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"                 % "0.11.0")
